language: node_js
sudo: false
node_js:
- '0.12'
before_script:
- npm install -g jspm
- npm install -g karma-cli
- npm install -g divshot-cli
- jspm config endpoints.github.auth $JSPM_AUTH
- jspm install
script:
- karma start karma.conf.js --single-run
deploy:
  provider: s3
  access_key_id: AKIAIAK7BMN6OCOVQNSQ
  secret_access_key:
    secure: E1t0tWysOUQgrCj3646fahQAq+3KEReatuVNULDcgpRJtx3jq2SEZrTWuOUU6vLJ0biViaVyOGwbEmsdC72eF2OBgZMq0lcLsGdoQBGejBxETmwfY/3PdwX9Cq3oKOpvRFDeQ3DdrOlgbjWlHqK+C2pBZ12NoOpJ1/PJ4Ox3Uv0=
  bucket: gdn-cdn
  upload-dir: /embed/aus/2015/mar/test-travis/
  acl: public_read
  local_dir: build
  on:
    repo: toddmoore/jspmtest
    all_branches: true
